name: stop_finder
description: A App to find nearby stops and real time status for transport.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  location: ^7.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true