name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  equatable: ^2.0.5
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  location: ^7.0.1
  # signalr_client: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true